name: Refresh GH Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger GitHub pages rebuild
        run: |
          for file in $(find -name '*.pdf'); do
            dir="${file%/*}"
            filename="${file%.*}"
            echo $dir
            echo $filename
            magick $file "$dir/$filename.png"
          done
       
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git commit -m "generating png"
            
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true