name: Refresh GH Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          for file in $(find -name '*.pdf'); do
            dir="${file%/*}"
            filename="${file%.*}"
            echo $dir
            echo $filename
            magick $file "$dir/$filename.png"
          done
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}