name: Refresh GH Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger GitHub pages rebuild
        run: |
          sudo apt-get install ghostscript
          sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml 
          for file in $(find -name '*.pdf'); do
            dir="${file%/*}"
            filename="${file%.*}"
            echo $dir
            echo $filename
            echo $file "$filename.png"
            convert -density 150 $file -quality 90 "$filename.png"
          done
       
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git add . 
          git commit -m "generating png"
            
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true